#!/usr/bin/env bash
# generate_font_header.sh — embed a .ttf as a compressed C header
#
# Regenerates a header in the same style as src/widgets/panel_font.h: builds
# imgui's vendored binary_to_compressed_c tool and runs it (-u32 encoding)
# against a TTF, then wraps the result in a namespace with this project's
# `k_<symbol>_compressed_*` naming convention.
#
# Neither sextant's plot/axes font (loaded from system font paths at
# runtime, see spec_build.md's Fonts section) nor its build normally needs
# this — it's only for embedding a new font asset the way panel_font.h
# embeds Roboto-Medium.ttf for the ImGui control panel.
#
# Usage:
#   scripts/generate_font_header.sh <input.ttf> <symbol_name> <output_header.h> [namespace]
#
# Example (regenerating the existing panel font):
#   scripts/generate_font_header.sh \
#       third_party/imgui/misc/fonts/Roboto-Medium.ttf \
#       roboto_medium \
#       src/widgets/panel_font.h \
#       sextant::panel_font

set -euo pipefail

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <input.ttf> <symbol_name> <output_header.h> [namespace]" >&2
    echo "Example: $0 third_party/imgui/misc/fonts/Roboto-Medium.ttf roboto_medium src/widgets/panel_font.h sextant::panel_font" >&2
    exit 1
fi

TTF_FILE="$1"
SYMBOL="$2"
OUT_HEADER="$3"
NAMESPACE="${4:-}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOL_SRC="$REPO_ROOT/third_party/imgui/misc/fonts/binary_to_compressed_c.cpp"

if [ ! -f "$TTF_FILE" ]; then
    echo "error: input font not found: $TTF_FILE" >&2
    exit 1
fi
if [ ! -f "$TOOL_SRC" ]; then
    echo "error: binary_to_compressed_c.cpp not found at $TOOL_SRC — run scripts/setup_deps.sh first" >&2
    exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "==> Building binary_to_compressed_c..."
TOOL_BIN="$WORK_DIR/b2c"
if command -v g++ >/dev/null 2>&1; then
    g++ -O2 -o "$TOOL_BIN" "$TOOL_SRC"
elif command -v clang++ >/dev/null 2>&1; then
    clang++ -O2 -o "$TOOL_BIN" "$TOOL_SRC"
elif command -v cl.exe >/dev/null 2>&1; then
    # cl.exe drops its output next to the input by default — build in WORK_DIR.
    ( cd "$WORK_DIR" && cl.exe /nologo /O2 /Fe:b2c.exe "$TOOL_SRC" >/dev/null )
    TOOL_BIN="$WORK_DIR/b2c.exe"
else
    echo "error: no C++ compiler found (need g++, clang++, or cl.exe on PATH — run from a vcvars64 session for cl.exe)" >&2
    exit 1
fi

echo "==> Compressing $TTF_FILE as '$SYMBOL' (-u32)..."
RAW_OUT="$WORK_DIR/raw.h"
"$TOOL_BIN" -u32 "$TTF_FILE" "$SYMBOL" > "$RAW_OUT"

mkdir -p "$(dirname "$OUT_HEADER")"
{
    echo "#pragma once"
    echo ""
    echo "// Generated by scripts/generate_font_header.sh from:"
    echo "//   $TTF_FILE"
    echo "// Regenerate with:"
    echo "//   scripts/generate_font_header.sh $TTF_FILE $SYMBOL $OUT_HEADER${NAMESPACE:+ $NAMESPACE}"
    echo "// Load with: ImGui::GetIO().Fonts->AddFontFromMemoryCompressedTTF(...)"
    echo ""
    if [ -n "$NAMESPACE" ]; then
        echo "namespace $NAMESPACE {"
        echo ""
    fi
    # Rename the tool's <symbol>_compressed_* variables to this project's
    # k_<symbol>_compressed_* convention (matches src/widgets/panel_font.h).
    sed \
        -e "s/${SYMBOL}_compressed_size/k_${SYMBOL}_compressed_size/g" \
        -e "s/${SYMBOL}_compressed_data/k_${SYMBOL}_compressed_data/g" \
        "$RAW_OUT"
    if [ -n "$NAMESPACE" ]; then
        echo "} // namespace $NAMESPACE"
    fi
} > "$OUT_HEADER"

echo "==> Wrote $OUT_HEADER"
SIZE_VAR="k_${SYMBOL}_compressed_size"
DATA_VAR="k_${SYMBOL}_compressed_data"
if [ -n "$NAMESPACE" ]; then
    SIZE_VAR="${NAMESPACE}::${SIZE_VAR}"
    DATA_VAR="${NAMESPACE}::${DATA_VAR}"
fi
echo "    Load with: io.Fonts->AddFontFromMemoryCompressedTTF(${DATA_VAR}, ${SIZE_VAR}, size_px);"
