#!/usr/bin/env python3
# generate_window_icon.py — rasterise the sextant icon into a C header
#
# Renders doc/icons/sextant-icon.svg at the sizes GLFW chooses between for a
# window icon and writes them as straight (non-premultiplied) RGBA8 byte arrays
# in src/window_icon.h, which window_broker.cpp hands to glfwSetWindowIcon().
# Only needed when the icon changes.
#
# Usage (from the repo root; uv fetches the two packages):
#   uv run --no-project --with pillow --with resvg-py python scripts/generate_window_icon.py

import io
import sys
from pathlib import Path

import resvg_py
from PIL import Image

SVG = "doc/icons/sextant-icon.svg"
OUT = "src/window_icon.h"
# Win32 picks the closest to the small (16/24/32) and big (32/48/64) icon size
# of the display's scale; X11 takes every one.
SIZES = (16, 24, 32, 48, 64)


def render(svg_path: Path, size: int) -> bytes:
    png = resvg_py.svg_to_bytes(svg_path=str(svg_path), width=size, height=size)
    # resvg's PNG is straight alpha, which is what GLFW expects.
    img = Image.open(io.BytesIO(bytes(png))).convert("RGBA")
    if img.size != (size, size):
        sys.exit(f"error: rendered {img.size}, expected {size}x{size}")
    return img.tobytes()


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    svg = root / SVG
    lines = [
        "#pragma once",
        "",
        f"// Generated by scripts/generate_window_icon.py from {SVG}. Do not edit;",
        "// regenerate (see the script) when the icon changes.",
        "// Straight RGBA8, row-major from the top-left, one image per size.",
        "",
        "namespace sextant::window_icon {",
    ]
    for size in SIZES:
        data = render(svg, size)
        lines.append(f"    inline constexpr unsigned char k_rgba_{size}[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            lines.append("        " + ",".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
        lines.append("    };")
        lines.append("")
    lines.append("    struct Image {")
    lines.append("        int size;")
    lines.append("        const unsigned char* rgba;")
    lines.append("    };")
    lines.append("")
    lines.append("    inline constexpr Image k_images[] = {")
    for size in SIZES:
        lines.append(f"        {{{size}, k_rgba_{size}}},")
    lines.append("    };")
    lines.append("} // namespace sextant::window_icon")
    lines.append("")
    (root / OUT).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({', '.join(map(str, SIZES))})")


if __name__ == "__main__":
    main()
